name: fuel_dashboard_env
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.1.0=pyhd8ed1ab_0
  - aio-pika=6.8.1=pyh6c4a22f_0
  - aiohappyeyeballs=2.4.3=pyhd8ed1ab_0
  - aiohttp=3.10.5=py38h3237794_0
  - aiormq=3.3.1=py_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alembic=1.14.0=pyhd8ed1ab_0
  - anyio=4.5.0=pyhd8ed1ab_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38hb192615_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_2
  - async-lru=2.0.4=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - aws-c-auth=0.7.3=h109ad1a_1
  - aws-c-cal=0.6.1=hb406d48_1
  - aws-c-common=0.9.0=hb547adb_0
  - aws-c-compression=0.2.17=he70778a_2
  - aws-c-event-stream=0.3.1=hcf14f3f_4
  - aws-c-http=0.7.11=hcbec455_4
  - aws-c-io=0.13.32=he8ad1d2_1
  - aws-c-mqtt=0.9.3=hf45dd20_1
  - aws-c-s3=0.3.14=hf0e1321_1
  - aws-c-sdkutils=0.1.12=he70778a_1
  - aws-checksums=0.1.17=he70778a_1
  - aws-crt-cpp=0.21.0=hda227cd_5
  - aws-sdk-cpp=1.10.57=h1190f42_19
  - babel=2.16.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - bayesian-optimization=1.4.3=pyhd8ed1ab_0
  - bcrypt=4.2.0=py38h186058e_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blinker=1.8.2=pyhd8ed1ab_0
  - bokeh=2.4.2=py38h10201cd_1
  - boto3=1.35.72=pyhd8ed1ab_0
  - botocore=1.35.99=pyge38_1234567_0
  - brotli=1.0.9=h1a8c8d9_9
  - brotli-bin=1.0.9=h1a8c8d9_9
  - brotli-python=1.0.9=py38h2b1e499_9
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.4=h5505292_0
  - ca-certificates=2025.1.31=hf0a4a13_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.5.0=pyhd8ed1ab_0
  - cartopy=0.21.1=py38h7b3d0a4_1
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38h858044d_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.1.0=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - configparser=7.1.0=pyhd8ed1ab_0
  - contourpy=1.1.1=py38h9afee92_1
  - cryptography=43.0.0=py38h4d1d993_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cytoolz=0.12.3=py38h336bac9_0
  - dash=2.18.2=pyhd8ed1ab_0
  - dash-bootstrap-components=1.6.0=pyhd8ed1ab_0
  - dask=2023.5.0=pyhd8ed1ab_0
  - dask-core=2023.5.0=pyhd8ed1ab_0
  - databricks-cli=0.17.8=pyhd8ed1ab_0
  - debugpy=1.8.5=py38h11842c7_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distributed=2023.5.0=pyhd8ed1ab_0
  - dnspython=2.6.1=pyhd8ed1ab_1
  - docker-py=7.1.0=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - flask=3.0.3=pyhd8ed1ab_0
  - flatbuffers=23.5.26=h13dd4ca_1
  - fonttools=4.53.1=py38h3237794_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.13.3=h1d14073_0
  - frozenlist=1.4.1=py38h336bac9_0
  - fsspec=2024.10.0=pyhff2d567_0
  - gast=0.4.0=pyh9f0ad1d_0
  - geographiclib=2.0=pyhd8ed1ab_0
  - geohash2=1.1=py_0
  - geopy=2.4.1=pyhd8ed1ab_1
  - geos=3.11.2=hb7217d7_0
  - gettext=0.23.1=h3dcc1bd_0
  - gettext-tools=0.23.1=h493aca8_0
  - gflags=2.2.2=hf9b8971_1005
  - giflib=5.2.2=h93a5062_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - glog=0.6.0=h6da1cb0_0
  - google-auth=2.35.0=pyhff2d567_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_1
  - google-pasta=0.2.0=pyhd8ed1ab_1
  - greenlet=3.0.3=py38hb9fa5a8_0
  - grpcio=1.54.3=py38he333c0f_0
  - gunicorn=23.0.0=py38h10201cd_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h3-py=3.7.7=py38hb9fa5a8_0
  - h5py=3.11.0=nompi_py38h70800c8_102
  - hdf5=1.14.3=nompi_ha698983_109
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.27.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=hc8870d7_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_metadata=8.5.0=hd8ed1ab_1
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.12.2=pyhd1c38e8_0
  - ipywidgets=8.1.5=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_0
  - jax=0.4.13=pyhd8ed1ab_0
  - jaxlib=0.4.12=cpu_py38h7aa3e66_1
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py38h10201cd_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter=1.1.1=pyhd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.2.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_0
  - keras=2.12.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py38h9afee92_1
  - krb5=1.21.3=h237132a_0
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libabseil=20230125.3=cxx17_h13dd4ca_0
  - libaec=1.1.3=hebf3989_0
  - libarrow=12.0.1=h0b136c2_8_cpu
  - libasprintf=0.23.1=h493aca8_0
  - libasprintf-devel=0.23.1=h493aca8_0
  - libblas=3.9.0=20_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1a8c8d9_9
  - libbrotlidec=1.0.9=h1a8c8d9_9
  - libbrotlienc=1.0.9=h1a8c8d9_9
  - libcblas=3.9.0=20_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.13.0=h73640d1_0
  - libcxx=20.1.2=ha82da77_0
  - libdeflate=1.21=h99b78c6_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libffi=3.4.6=h1da3d7d_1
  - libgettextpo=0.23.1=h493aca8_0
  - libgettextpo-devel=0.23.1=h493aca8_0
  - libgfortran=14.2.0=heb5dd2a_105
  - libgfortran5=14.2.0=h2c44a93_105
  - libgoogle-cloud=2.12.0=he22f4c0_1
  - libgrpc=1.54.3=h0a338ca_0
  - libiconv=1.18=hfe07756_1
  - libintl=0.23.1=h493aca8_0
  - libintl-devel=0.23.1=h493aca8_0
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=20_osxarm64_openblas
  - libllvm14=14.0.6=hd1a9a77_4
  - liblzma=5.8.1=h39f12f2_0
  - liblzma-devel=5.8.1=h39f12f2_0
  - libnghttp2=1.64.0=h6d7220d_0
  - libopenblas=0.3.25=openmp_h6c19121_0
  - libpng=1.6.47=h3783ad8_0
  - libprotobuf=3.21.12=ha614eb4_2
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.49.1=h3f77e49_2
  - libssh2=1.11.1=h9cc3647_0
  - libthrift=0.18.1=ha061701_2
  - libtiff=4.6.0=hf8409c0_4
  - libutf8proc=2.8.0=hc098a78_1
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=20.1.2=hdb05f8b_0
  - llvmlite=0.41.1=py38hbed3d3f_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py38h94f39dc_0
  - lz4-c=1.9.4=hb7217d7_0
  - mako=1.3.5=pyhd8ed1ab_0
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py38h336bac9_0
  - matplotlib=3.7.3=py38h150bfb4_0
  - matplotlib-base=3.7.3=py38hef9d0d7_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - ml_dtypes=0.2.0=py38h181dcb6_2
  - mlflow=1.26.1=py38h64755cf_0
  - motor=3.5.1=pyhd8ed1ab_0
  - multidict=6.0.5=py38hb991d35_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhff2d567_2
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - notebook=7.2.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numba=0.58.1=py38hbe32c8a_0
  - numpy=1.24.4=py38ha84db1f_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.2=h9f1df11_0
  - openssl=3.4.1=h81ee809_0
  - opt_einsum=3.4.0=pyhd8ed1ab_0
  - orc=1.9.0=ha98e9e8_1
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.2=pyhd8ed1ab_2
  - pamqp=2.3.0=py_0
  - pandas=1.4.4=py38h2a4bfaf_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - paramiko=3.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - partd=1.4.1=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py38h2c6aaed_0
  - pip=24.3.1=pyh8b19718_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - plotly=5.24.1=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - proj=8.2.1=hb8d25fd_0
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - protobuf=4.21.12=py38h2b1e499_0
  - psutil=6.0.0=py38h3237794_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pyarrow=12.0.1=py38h5809dd6_8_cpu
  - pyasn1=0.6.1=pyhd8ed1ab_1
  - pyasn1-modules=0.4.1=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pydash=8.0.4=pyhff2d567_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyjwt=2.9.0=pyhd8ed1ab_1
  - pymongo=4.8.0=py38h11842c7_0
  - pynacl=1.5.0=py38hb192615_3
  - pyobjc-core=10.1=py38h80987f9_0
  - pyobjc-framework-cocoa=10.1=py38hb094c41_0
  - pyopenssl=24.2.1=pyhd8ed1ab_2
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyproj=3.3.0=py38h4b69435_1
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.20=h7d35d02_2_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-flatbuffers=24.3.25=pyh59ac667_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.8=6_cp38
  - pytz=2024.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.2=py38h3237794_0
  - pyzmq=26.2.0=py38h7e0d939_0
  - querystring_parser=1.2.4=pyhd8ed1ab_1
  - re2=2023.03.02=hc5e2d97_0
  - readline=8.2=h1d1bf99_2
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - retrying=1.3.3=pyhd8ed1ab_3
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.20.0=py38h186058e_0
  - rsa=4.9=pyhd8ed1ab_0
  - ruptures=1.1.9=py38h9f76b62_2
  - s3transfer=0.10.4=pyhd8ed1ab_0
  - scikit-learn=1.2.0=py38h0c332d6_0
  - scipy=1.10.1=py38h038e806_3
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - send2trash=1.8.3=pyh31c8845_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - shapely=2.0.1=py38h460ca9b_1
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.10=hd04f947_1
  - sniffio=1.3.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlalchemy=2.0.24=py38h336bac9_0
  - sqlite=3.49.1=hd7222ec_2
  - sqlparse=0.5.1=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.1=py38h691f20f_0
  - supervisor=4.2.1=py38h10201cd_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tblib=3.0.0=pyhd8ed1ab_0
  - tenacity=9.0.0=pyhd8ed1ab_0
  - tensorboard=2.12.3=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py38h92a0862_1
  - tensorflow=2.12.1=cpu_py38h4487131_1
  - tensorflow-base=2.12.1=cpu_py38h7de3861_1
  - tensorflow-estimator=2.12.1=cpu_py38hceb852f_1
  - termcolor=2.4.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - timezonefinder=6.5.2=py38h3237794_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tomli=2.0.2=pyhd8ed1ab_0
  - toolz=1.0.0=pyhd8ed1ab_0
  - tornado=6.4.1=py38h3237794_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20241003=pyhff2d567_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - unicodedata2=15.1.0=py38hb192615_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=1.26.19=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - werkzeug=3.0.6=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_0
  - wrapt=1.16.0=py38h336bac9_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.8.1=h9a6d368_0
  - xz-gpl-tools=5.8.1=h9a6d368_0
  - xz-tools=5.8.1=h39f12f2_0
  - yaml=0.2.5=h3422bc3_2
  - yarl=1.9.4=py38h336bac9_0
  - zeromq=4.3.5=hcc0f68c_4
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - streamlit
            - et-xmlfile==2.0.0
      - future==1.0.0
      - gevent==24.2.1
      - msgpack==0.6.2
      - openpyxl==3.1.5
      - outcome==1.3.0.post0
      - pdfme==0.4.12
      - selenium==4.27.1
      - trio==0.27.0
      - trio-websocket==0.12.2
      - typing-extensions==4.13.2
      - wsproto==1.2.0
      - xlrd==2.0.1
      - zerorpc==0.6.3
      - zope-event==5.0
      - zope-interface==7.2
