name: fuel_dashboard_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - requests
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - pip
  - pip:
      - streamlit
<<<<<<< HEAD
      - streamlit_autorefresh
=======
      - streamlit-autorefresh
>>>>>>> 151deb6 (Update environment.yml)
